steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['clean', 'package']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/recognition-translate:${_VERSION}', '-t', 'eu.gcr.io/$PROJECT_ID/recognition-translate:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/$PROJECT_ID/recognition-translate:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/$PROJECT_ID/recognition-translate:${_VERSION}']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['endpoints',  'services', 'deploy', 'endpoints.yaml']
- name: 'ubuntu'
  args: ['bash','-c','sed -i s/APP_VERSION/${_VERSION}/g deployment.yaml']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'deployment.yaml']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west2-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=reko-cluster'
substitutions:
  _VERSION: 0.1.2.4
timeout: 600s
tags: ['recognition', 'translate']