
apiVersion: v1
kind: Service
metadata:
  name: translate-svc
spec:
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: esp-translate
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: esp-translate
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: esp-translate
    spec:
      containers:
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "--http_port=8081",
          "--backend=127.0.0.1:8080",
          "--service=translate.just2teach.com",
          "--rollout_strategy=managed",
        ]
        ports:
        - containerPort: 8081
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 40
          periodSeconds: 10
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/etc/creds/reko.json"
        volumeMounts:
        - name: creds
          mountPath: "/etc/creds"
          readOnly: true
      - name: translate
        image: eu.gcr.io/recognition-218419/recognition-translate:APP_VERSION
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/etc/creds/reko.json"
        - name: GOOGLE_CLOUD_PROJECT
          value: "XXXXXXXXXXX"
        - name: TOPIC
          value: "reko-recorder"
        volumeMounts:
        - name: creds
          mountPath: "/etc/creds"
          readOnly: true
        ports:
          - containerPort: 8080
      imagePullSecrets:
      - name: auth-gcr
      volumes:
        - name: creds
          secret:
            secretName: auth-gcp